# Generated by Django 6.0.4 on 2026-05-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='petrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_requests/'),
        ),
    ]
