# Generated by Django 6.0.4 on 2026-05-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
